---
output: github_document
---
# YWCC-307
This README serves as this repository's cover page.

This repository consists of my individual presentation from YWCC 307 and the course's syllabus.
The presentation is about managing non-traditional software teams.
In this presentation I go over the general phases of the software development lifecyle. 
I then shift focus on two different software development lifecycle models: Waterfall and Agile and then talk about the main differences between the two.
I also go over the pros and cons of the two lifecyle models and explain why Agile is now the industry de facto in software development.
Additionally, I talk about the 6 steps in Agile methodologies from a project manager's perspective and the scrum framework used in agile development.
I then shift focus to talk about agile methodolgies from a software developer's perspective. 
Lastly, I conclude the presentation with a summary on how using Agile methodolgies helps to deliver a better product and how it helps with team productivity
and the products overall quality.
